# Generated by Django 3.1.7 on 2021-02-28 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Транслит')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Транслит')),
                ('photo', models.ImageField(upload_to='upload/product/photos/%Y/%m/%d/', verbose_name='Фото')),
                ('content', models.TextField(verbose_name='Описание')),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('availability', models.BooleanField(verbose_name='Наличие')),
                ('discount', models.IntegerField(verbose_name='Скидка в %')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория')),
            ],
        ),
    ]
