# Generated by Django 3.1.7 on 2021-03-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210228_2255'),
        ('shop', '0003_auto_20210228_2259'),
    ]

    operations = [
    ]
